### ISSUE TITLE
Ubuntu build instruction

### ISSUE THREAD

**Issue by PaulVanSchayck** [ilarik/kanki-irodsclient#1]
Building for Ubuntu 15.04 did not cause many issues:

```
sudo apt-get install qt5-qmake qtbase5-dev libqt5svg5-dev libcurl4-nss-dev qt5-default
qmake
make
```

Howerver, the qt5-default package is crucial. Otherwise qmake was linked to qt4 for me. The direct location of qt5 qmake was: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake.

Personally I prefer these kind of instructions over a wrapper script like build.sh wrapping arround qmake and make. 

The client works excellent and looks great. Keep up the good work!

**Comment by ilarik** [comment]
Thank you very much for this information! 

I tested the Ubuntu build on 14.04 LTS and it works exactly as you outlined and I added the instructions to the git repo README and gave you credit for it. Just released a new version 1.0.4 with an improved download plus other minor enhancements and bug fixes. I hope you get to try it out! 

Thanks a lot for the (positive) feedback, I'll try my best, and currently I'm thinking the fun is just about to start so stay tuned!
