### ISSUE TITLE
Put not working

### ISSUE THREAD

**Issue by danilomo** [ilarik/kanki-irodsclient#3]
The method:

int RodsConnection::putFile(const std::string &localPath, const std::string &objPath, const std::string &rodsResc, unsigned int numThreads)

isn't working.

When I try to perform some upload, it is returning the following message:

"Put failed
Status: -130000"

(I'm now using a CentOS operating system, since I wasn't able to build using Ubuntu)

**Comment by ilarik** [comment]
There is a bug in resource selection, the client doesn't now handle one case properly - the case when user doesn't provide the default resource in ~/.irods/irods_environment.json. Patch coming up. Thanks!

In the mean time you can go around the issue by defining irods_default_resource in your environment file to what you are using (in case a clean install of irods it is demoResc). Please let me know if this works.

**Comment by danilomo** [comment]
Yes!!! It's working!

Thank you, sir!

**Comment by ilarik** [comment]
This is now fixed. Commits in develop branch to be included in the next patch release.
