### ISSUE TITLE
Kanki should prevent user from trying to write to a leaf resource

### ISSUE THREAD

**Issue by bandebard** [ilarik/kanki-irodsclient#4]
When I compose a resource tree, iRODS (correctly) prohibits me from writing to children of coordinating resources--it will only allow me to write to the root node.

Kanki correctly passes this error along to the user (-1816000), but would be helpful if the leaf nodes were grayed out to begin with.

**Comment by ilarik** [comment]
Thanks, I had forgotten this already, the resource selection feature was a bit quick and dirty. It's definitely better to expose only writable resources to the user. Fix committed to the develop branch: only show resources which have no parent. Is this the correct behaviour? That is when a resource gets a parent it becomes inaccessible directly?

**Comment by bandebard** [comment]
I haven't tested the code yet, but your description is correct.
