### ISSUE TITLE
Interface does not have quit menu action/shortcut on non-macos

### ISSUE THREAD

**Issue by petergil** [ilarik/kanki-irodsclient#7]
I have created pull request #6, which adds these.

Not tested on macOS to see if the interface stays consistent with macos guidelines.

**Comment by ilarik** [comment]
@Peter, I just pulled your awesome request and what can I say, this is very good. I have no objections to how you solved this.

I'm very happy about this!

**Comment by ilarik** [comment]
Merged the pull request #6 successfully and works very nicely!
